# CPU spoof must never apply to these packages.
com.bbl.mobilebanking
com.android.settings
com.android.vending
com.google.android.gms
com.google.android.gsf
com.google.android.apps.walletnfcrel
com.oplus.camera
com.android.camera
com.coloros.camera
com.heytap.market
com.finshell.wallet
